{
    "org.jfree.chart.plot.Plot": [
        {
            "resolveRangeAxisLocation(org.jfree.chart.axis.AxisLocation, org.jfree.chart.plot.PlotOrientation)": [
                {
                    "ENTER": [
                        {
                            "Patch91.inv.output": {
                                "invs": [
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT != null",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "location != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT.name != null",
                                    "orientation != null",
                                    "location.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL.name != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT.name != null",
                                    "orientation.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT.name != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        },
                        {
                            "Patch14.inv.output": {
                                "invs": [
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT != null",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "location != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT.name != null",
                                    "orientation != null",
                                    "location.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL.name != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT.name != null",
                                    "orientation.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT.name != null"
                                ]
                            }
                        },
                        {
                            "f.inv.output": {
                                "invs": [
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT != null",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "location != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT.name != null",
                                    "orientation != null",
                                    "location.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL.name != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT.name != null",
                                    "orientation.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT.name != null"
                                ]
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "Patch91.inv.output": {
                                "invs": [
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT != null",
                                    "return.name != null",
                                    "return != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT != null",
                                    "org.jfree.chart.util.RectangleEdge.RIGHT.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL.name != null",
                                    "org.jfree.chart.util.RectangleEdge.TOP.name != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL.name != null",
                                    "location.name != null",
                                    "org.jfree.chart.util.RectangleEdge.BOTTOM.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT != null",
                                    "org.jfree.chart.util.RectangleEdge.RIGHT != null",
                                    "org.jfree.chart.util.RectangleEdge.TOP != null",
                                    "org.jfree.chart.util.RectangleEdge.LEFT.name != null",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT.name != null",
                                    "org.jfree.chart.util.RectangleEdge.BOTTOM != null",
                                    "orientation.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT.name != null",
                                    "org.jfree.chart.util.RectangleEdge.LEFT != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        },
                        {
                            "Patch14.inv.output": {
                                "invs": [
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT != null",
                                    "return.name != null",
                                    "return != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT != null",
                                    "org.jfree.chart.util.RectangleEdge.RIGHT.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL.name != null",
                                    "org.jfree.chart.util.RectangleEdge.TOP.name != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL.name != null",
                                    "location.name != null",
                                    "org.jfree.chart.util.RectangleEdge.BOTTOM.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT != null",
                                    "org.jfree.chart.util.RectangleEdge.RIGHT != null",
                                    "org.jfree.chart.util.RectangleEdge.TOP != null",
                                    "org.jfree.chart.util.RectangleEdge.LEFT.name != null",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT.name != null",
                                    "org.jfree.chart.util.RectangleEdge.BOTTOM != null",
                                    "orientation.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT.name != null",
                                    "org.jfree.chart.util.RectangleEdge.LEFT != null"
                                ]
                            }
                        },
                        {
                            "f.inv.output": {
                                "invs": [
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT != null",
                                    "return.name != null",
                                    "return != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT != null",
                                    "org.jfree.chart.util.RectangleEdge.RIGHT.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL.name != null",
                                    "org.jfree.chart.util.RectangleEdge.TOP.name != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL.name != null",
                                    "location.name != null",
                                    "org.jfree.chart.util.RectangleEdge.BOTTOM.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT != null",
                                    "org.jfree.chart.util.RectangleEdge.RIGHT != null",
                                    "org.jfree.chart.util.RectangleEdge.TOP != null",
                                    "org.jfree.chart.util.RectangleEdge.LEFT.name != null",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT.name != null",
                                    "org.jfree.chart.util.RectangleEdge.BOTTOM != null",
                                    "orientation.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT.name != null",
                                    "org.jfree.chart.util.RectangleEdge.LEFT != null"
                                ]
                            }
                        }
                    ]
                }
            ]
        },
        {
            "notifyListeners(org.jfree.chart.event.PlotChangeEvent)": [
                {
                    "ENTER": [
                        {
                            "Patch91.inv.output": {
                                "invs": [
                                    "org.jfree.chart.event.ChartChangeEventType.DATASET_UPDATED != null",
                                    "event.plot != null",
                                    "org.jfree.chart.event.ChartChangeEventType.NEW_DATASET != null",
                                    "event.plot.backgroundPaint != null",
                                    "org.jfree.chart.event.ChartChangeEventType.GENERAL != null",
                                    "event.plot.outlineStroke != null",
                                    "event.plot.noDataMessagePaint != null",
                                    "event.type.name != null",
                                    "event.plot.insets != null",
                                    "event != null",
                                    "event.plot.listenerList != null",
                                    "event.plot.outlinePaint != null",
                                    "event.type != null",
                                    "event.plot.noDataMessageFont != null",
                                    "event.plot.drawingSupplier != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        },
                        {
                            "Patch14.inv.output": {
                                "invs": [
                                    "org.jfree.chart.event.ChartChangeEventType.DATASET_UPDATED != null",
                                    "event.plot != null",
                                    "org.jfree.chart.event.ChartChangeEventType.NEW_DATASET != null",
                                    "event.plot.backgroundPaint != null",
                                    "org.jfree.chart.event.ChartChangeEventType.GENERAL != null",
                                    "event.plot.outlineStroke != null",
                                    "event.plot.noDataMessagePaint != null",
                                    "event.type.name != null",
                                    "event.plot.insets != null",
                                    "event != null",
                                    "event.plot.listenerList != null",
                                    "event.plot.outlinePaint != null",
                                    "event.type != null",
                                    "event.plot.noDataMessageFont != null",
                                    "event.plot.drawingSupplier != null"
                                ]
                            }
                        },
                        {
                            "f.inv.output": {
                                "invs": [
                                    "org.jfree.chart.event.ChartChangeEventType.DATASET_UPDATED != null",
                                    "event.plot != null",
                                    "org.jfree.chart.event.ChartChangeEventType.NEW_DATASET != null",
                                    "event.plot.backgroundPaint != null",
                                    "org.jfree.chart.event.ChartChangeEventType.GENERAL != null",
                                    "event.plot.outlineStroke != null",
                                    "event.plot.noDataMessagePaint != null",
                                    "event.type.name != null",
                                    "event.plot.insets != null",
                                    "event != null",
                                    "event.plot.listenerList != null",
                                    "event.plot.outlinePaint != null",
                                    "event.type != null",
                                    "event.plot.noDataMessageFont != null",
                                    "event.plot.drawingSupplier != null"
                                ]
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "Patch91.inv.output": {
                                "invs": [
                                    "org.jfree.chart.event.ChartChangeEventType.DATASET_UPDATED != null",
                                    "event.type != null",
                                    "event.plot != null",
                                    "org.jfree.chart.event.ChartChangeEventType.GENERAL != null",
                                    "event.plot.backgroundPaint != null",
                                    "event.plot.outlineStroke != null",
                                    "event.plot.noDataMessagePaint != null",
                                    "event.type.name != null",
                                    "event.plot.insets != null",
                                    "event.plot.listenerList != null",
                                    "event.plot.outlinePaint != null",
                                    "org.jfree.chart.event.ChartChangeEventType.NEW_DATASET != null",
                                    "event.plot.noDataMessageFont != null",
                                    "event.plot.drawingSupplier != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        },
                        {
                            "Patch14.inv.output": {
                                "invs": [
                                    "org.jfree.chart.event.ChartChangeEventType.DATASET_UPDATED != null",
                                    "event.type != null",
                                    "event.plot != null",
                                    "org.jfree.chart.event.ChartChangeEventType.GENERAL != null",
                                    "event.plot.backgroundPaint != null",
                                    "event.plot.outlineStroke != null",
                                    "event.plot.noDataMessagePaint != null",
                                    "event.type.name != null",
                                    "event.plot.insets != null",
                                    "event.plot.listenerList != null",
                                    "event.plot.outlinePaint != null",
                                    "org.jfree.chart.event.ChartChangeEventType.NEW_DATASET != null",
                                    "event.plot.noDataMessageFont != null",
                                    "event.plot.drawingSupplier != null"
                                ]
                            }
                        },
                        {
                            "f.inv.output": {
                                "invs": [
                                    "org.jfree.chart.event.ChartChangeEventType.DATASET_UPDATED != null",
                                    "event.type != null",
                                    "event.plot != null",
                                    "org.jfree.chart.event.ChartChangeEventType.GENERAL != null",
                                    "event.plot.backgroundPaint != null",
                                    "event.plot.outlineStroke != null",
                                    "event.plot.noDataMessagePaint != null",
                                    "event.type.name != null",
                                    "event.plot.insets != null",
                                    "event.plot.listenerList != null",
                                    "event.plot.outlinePaint != null",
                                    "org.jfree.chart.event.ChartChangeEventType.NEW_DATASET != null",
                                    "event.plot.noDataMessageFont != null",
                                    "event.plot.drawingSupplier != null"
                                ]
                            }
                        }
                    ]
                }
            ]
        },
        {
            "resolveDomainAxisLocation(org.jfree.chart.axis.AxisLocation, org.jfree.chart.plot.PlotOrientation)": [
                {
                    "ENTER": [
                        {
                            "Patch91.inv.output": {
                                "invs": [
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT != null",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "location != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT.name != null",
                                    "orientation != null",
                                    "location.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL.name != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT.name != null",
                                    "orientation.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT.name != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        },
                        {
                            "Patch14.inv.output": {
                                "invs": [
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT != null",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "location != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT.name != null",
                                    "orientation != null",
                                    "location.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL.name != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT.name != null",
                                    "orientation.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT.name != null"
                                ]
                            }
                        },
                        {
                            "f.inv.output": {
                                "invs": [
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT != null",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "location != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT.name != null",
                                    "orientation != null",
                                    "location.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL.name != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT.name != null",
                                    "orientation.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT.name != null"
                                ]
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "Patch91.inv.output": {
                                "invs": [
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT != null",
                                    "return.name != null",
                                    "return != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT != null",
                                    "org.jfree.chart.util.RectangleEdge.RIGHT.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL.name != null",
                                    "org.jfree.chart.util.RectangleEdge.TOP.name != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL.name != null",
                                    "location.name != null",
                                    "org.jfree.chart.util.RectangleEdge.BOTTOM.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT != null",
                                    "org.jfree.chart.util.RectangleEdge.RIGHT != null",
                                    "org.jfree.chart.util.RectangleEdge.TOP != null",
                                    "org.jfree.chart.util.RectangleEdge.LEFT.name != null",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT.name != null",
                                    "org.jfree.chart.util.RectangleEdge.BOTTOM != null",
                                    "orientation.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT.name != null",
                                    "org.jfree.chart.util.RectangleEdge.LEFT != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        },
                        {
                            "Patch14.inv.output": {
                                "invs": [
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT != null",
                                    "return.name != null",
                                    "return != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT != null",
                                    "org.jfree.chart.util.RectangleEdge.RIGHT.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL.name != null",
                                    "org.jfree.chart.util.RectangleEdge.TOP.name != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL.name != null",
                                    "location.name != null",
                                    "org.jfree.chart.util.RectangleEdge.BOTTOM.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT != null",
                                    "org.jfree.chart.util.RectangleEdge.RIGHT != null",
                                    "org.jfree.chart.util.RectangleEdge.TOP != null",
                                    "org.jfree.chart.util.RectangleEdge.LEFT.name != null",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT.name != null",
                                    "org.jfree.chart.util.RectangleEdge.BOTTOM != null",
                                    "orientation.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT.name != null",
                                    "org.jfree.chart.util.RectangleEdge.LEFT != null"
                                ]
                            }
                        },
                        {
                            "f.inv.output": {
                                "invs": [
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT != null",
                                    "return.name != null",
                                    "return != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT != null",
                                    "org.jfree.chart.util.RectangleEdge.RIGHT.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL.name != null",
                                    "org.jfree.chart.util.RectangleEdge.TOP.name != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_LEFT.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL.name != null",
                                    "location.name != null",
                                    "org.jfree.chart.util.RectangleEdge.BOTTOM.name != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_RIGHT != null",
                                    "org.jfree.chart.util.RectangleEdge.RIGHT != null",
                                    "org.jfree.chart.util.RectangleEdge.TOP != null",
                                    "org.jfree.chart.util.RectangleEdge.LEFT.name != null",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "org.jfree.chart.axis.AxisLocation.TOP_OR_LEFT.name != null",
                                    "org.jfree.chart.util.RectangleEdge.BOTTOM != null",
                                    "orientation.name != null",
                                    "org.jfree.chart.plot.PlotOrientation.HORIZONTAL != null",
                                    "org.jfree.chart.plot.PlotOrientation.VERTICAL != null",
                                    "org.jfree.chart.axis.AxisLocation.BOTTOM_OR_RIGHT.name != null",
                                    "org.jfree.chart.util.RectangleEdge.LEFT != null"
                                ]
                            }
                        }
                    ]
                }
            ]
        }
    ]
}