{
    "org.jfree.chart.plot.Plot": [
        {
            "fillBackground(java.awt.Graphics2D, java.awt.geom.Rectangle2D, org.jfree.chart.plot.PlotOrientation)": [
                {
                    "EXITNN": [
                        {
                            "991": [
                                {
                                    "Patch13.inv.output": "N/A"
                                },
                                {
                                    "b.inv.output": {
                                        "invs": []
                                    }
                                },
                                {
                                    "Patch12.inv.output": "N/A"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}