{
    "org.jfree.chart.plot.Plot": [
        {
            "fillBackground(java.awt.Graphics2D, java.awt.geom.Rectangle2D, org.jfree.chart.plot.PlotOrientation)": [
                {
                    "EXITNN": [
                        {
                            "992": [
                                {
                                    "Patch93.inv.output": "N/A"
                                },
                                {
                                    "b.inv.output": {
                                        "invs": []
                                    }
                                },
                                {
                                    "Patch18.inv.output": "N/A"
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "class$(java.lang.String)": [
                {
                    "ENTER": [
                        {
                            "Patch93.inv.output": {
                                "invs": []
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": [
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener == null"
                                ]
                            }
                        },
                        {
                            "Patch18.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "Patch93.inv.output": {
                                "invs": []
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": [
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener == null"
                                ]
                            }
                        },
                        {
                            "Patch18.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                }
            ]
        }
    ]
}