{
    "org.jfree.chart.plot.Plot": [
        {
            "fillBackground(java.awt.Graphics2D, java.awt.geom.Rectangle2D, org.jfree.chart.plot.PlotOrientation)": [
                {
                    "ENTER": [
                        {
                            "Patch13.inv.output": {
                                "invs": [
                                    "area has only one value",
                                    "this.listenerList has only one value",
                                    "g2 has only one value",
                                    "this.getClass().getName() == org.jfree.chart.plot.PiePlot.class",
                                    "this.insets has only one value",
                                    "this.drawingSupplier has only one value",
                                    "this.noDataMessageFont has only one value",
                                    "this has only one value"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "Patch13.inv.output": {
                                "invs": [
                                    "this.insets has only one value",
                                    "this.drawingSupplier has only one value",
                                    "this.listenerList has only one value",
                                    "this.noDataMessageFont has only one value"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                },
                {
                    "EXITNN": [
                        {
                            "991": [
                                {
                                    "Patch13.inv.output": {
                                        "invs": []
                                    }
                                },
                                {
                                    "b.inv.output": {
                                        "invs": []
                                    }
                                },
                                {
                                    "Patch12.inv.output": "N/A"
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "drawBackgroundImage(java.awt.Graphics2D, java.awt.geom.Rectangle2D)": [
                {
                    "ENTER": [
                        {
                            "Patch13.inv.output": {
                                "invs": [
                                    "area has only one value",
                                    "this.listenerList has only one value",
                                    "g2 has only one value",
                                    "this.getClass().getName() == org.jfree.chart.plot.PiePlot.class",
                                    "this.insets has only one value",
                                    "this.drawingSupplier has only one value",
                                    "this.noDataMessageFont has only one value",
                                    "this has only one value"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "Patch13.inv.output": {
                                "invs": [
                                    "this.insets has only one value",
                                    "this.drawingSupplier has only one value",
                                    "this.listenerList has only one value",
                                    "this.noDataMessageFont has only one value"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                }
            ]
        },
        {
            "fillBackground(java.awt.Graphics2D, java.awt.geom.Rectangle2D)": [
                {
                    "ENTER": [
                        {
                            "Patch13.inv.output": {
                                "invs": [
                                    "area has only one value",
                                    "this.listenerList has only one value",
                                    "g2 has only one value",
                                    "this.getClass().getName() == org.jfree.chart.plot.PiePlot.class",
                                    "this.insets has only one value",
                                    "this.drawingSupplier has only one value",
                                    "this.noDataMessageFont has only one value",
                                    "this has only one value"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "Patch13.inv.output": {
                                "invs": [
                                    "this.insets has only one value",
                                    "this.drawingSupplier has only one value",
                                    "this.listenerList has only one value",
                                    "this.noDataMessageFont has only one value"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                }
            ]
        },
        {
            "getForegroundAlpha()": [
                {
                    "ENTER": [
                        {
                            "Patch13.inv.output": {
                                "invs": [
                                    "this.listenerList has only one value",
                                    "this.getClass().getName() == org.jfree.chart.plot.PiePlot.class",
                                    "this.insets has only one value",
                                    "this.drawingSupplier has only one value",
                                    "this.noDataMessageFont has only one value",
                                    "this has only one value"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "Patch13.inv.output": {
                                "invs": [
                                    "this.insets has only one value",
                                    "this.drawingSupplier has only one value",
                                    "this.listenerList has only one value",
                                    "this.noDataMessageFont has only one value"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                }
            ]
        },
        {
            "getInsets()": [
                {
                    "ENTER": [
                        {
                            "Patch13.inv.output": {
                                "invs": [
                                    "this.listenerList has only one value",
                                    "this.getClass().getName() == org.jfree.chart.plot.PiePlot.class",
                                    "this.insets has only one value",
                                    "this.drawingSupplier has only one value",
                                    "this.noDataMessageFont has only one value",
                                    "this has only one value"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "Patch13.inv.output": {
                                "invs": [
                                    "this.listenerList has only one value",
                                    "this.insets has only one value",
                                    "this.drawingSupplier has only one value",
                                    "this.noDataMessageFont has only one value",
                                    "return has only one value"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                }
            ]
        },
        {
            "drawBackground(java.awt.Graphics2D, java.awt.geom.Rectangle2D)": [
                {
                    "ENTER": [
                        {
                            "Patch13.inv.output": {
                                "invs": [
                                    "area has only one value",
                                    "this.listenerList has only one value",
                                    "g2 has only one value",
                                    "this.getClass().getName() == org.jfree.chart.plot.PiePlot.class",
                                    "this.insets has only one value",
                                    "this.drawingSupplier has only one value",
                                    "this.noDataMessageFont has only one value",
                                    "this has only one value"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "Patch13.inv.output": {
                                "invs": [
                                    "this.insets has only one value",
                                    "this.drawingSupplier has only one value",
                                    "this.listenerList has only one value",
                                    "this.noDataMessageFont has only one value"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                }
            ]
        },
        {
            "drawOutline(java.awt.Graphics2D, java.awt.geom.Rectangle2D)": [
                {
                    "ENTER": [
                        {
                            "Patch13.inv.output": {
                                "invs": [
                                    "area has only one value",
                                    "this.listenerList has only one value",
                                    "g2 has only one value",
                                    "this.getClass().getName() == org.jfree.chart.plot.PiePlot.class",
                                    "this.insets has only one value",
                                    "this.drawingSupplier has only one value",
                                    "this.noDataMessageFont has only one value",
                                    "this has only one value"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "Patch13.inv.output": {
                                "invs": [
                                    "this.insets has only one value",
                                    "this.drawingSupplier has only one value",
                                    "this.listenerList has only one value",
                                    "this.noDataMessageFont has only one value"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                },
                {
                    "EXITNN": [
                        {
                            "1038": [
                                {
                                    "Patch13.inv.output": {
                                        "invs": []
                                    }
                                },
                                {
                                    "b.inv.output": {
                                        "invs": []
                                    }
                                },
                                {
                                    "Patch12.inv.output": "N/A"
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "getParent()": [
                {
                    "ENTER": [
                        {
                            "Patch12.inv.output": {
                                "invs": [
                                    "this.listenerList has only one value",
                                    "this.getClass().getName() == org.jfree.chart.plot.PiePlot3D.class",
                                    "this.insets has only one value",
                                    "this.drawingSupplier has only one value",
                                    "this.noDataMessageFont has only one value",
                                    "this has only one value"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "Patch12.inv.output": {
                                "invs": [
                                    "this.insets has only one value",
                                    "this.drawingSupplier has only one value",
                                    "this.listenerList has only one value",
                                    "this.noDataMessageFont has only one value"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                }
            ]
        },
        {
            "getDrawingSupplier()": [
                {
                    "ENTER": [
                        {
                            "Patch12.inv.output": {
                                "invs": [
                                    "this.listenerList has only one value",
                                    "this.getClass().getName() == org.jfree.chart.plot.PiePlot3D.class",
                                    "this.insets has only one value",
                                    "this.drawingSupplier has only one value",
                                    "this.noDataMessageFont has only one value",
                                    "this has only one value"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "Patch12.inv.output": {
                                "invs": [
                                    "this.listenerList has only one value",
                                    "this.insets has only one value",
                                    "this.drawingSupplier has only one value",
                                    "this.noDataMessageFont has only one value",
                                    "return has only one value"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                }
            ]
        }
    ]
}