{
    "org.jfree.chart.plot.Plot": [
        {
            "getParent()": [
                {
                    "ENTER": [
                        {
                            "Patch86.inv.output": {
                                "invs": [
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.outlineStroke != null",
                                    "this.outlinePaint != null",
                                    "this.backgroundPaint != null",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.outlineVisible == true",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.insets != null",
                                    "this.noDataMessagePaint != null",
                                    "this.backgroundAlpha == 1.0",
                                    "this.listenerList != null",
                                    "this.outlinePaint has only one value",
                                    "this.drawingSupplier != null",
                                    "this.noDataMessageFont != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        },
                        {
                            "f.inv.output": {
                                "invs": [
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.outlineStroke != null",
                                    "this.outlinePaint != null",
                                    "this.backgroundPaint != null",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.outlineVisible == true",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.insets != null",
                                    "this.noDataMessagePaint != null",
                                    "this.backgroundAlpha == 1.0",
                                    "this.listenerList != null",
                                    "this.outlinePaint has only one value",
                                    "this.drawingSupplier != null",
                                    "this.noDataMessageFont != null"
                                ]
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "Patch86.inv.output": {
                                "invs": [
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.outlineStroke != null",
                                    "this.outlinePaint != null",
                                    "this.backgroundPaint != null",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.outlineVisible == true",
                                    "this.insets != null",
                                    "this.backgroundAlpha == 1.0",
                                    "this.drawingSupplier != null",
                                    "this.outlinePaint has only one value",
                                    "this.listenerList != null",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.noDataMessagePaint != null",
                                    "this.noDataMessageFont != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        },
                        {
                            "f.inv.output": {
                                "invs": [
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.outlineStroke != null",
                                    "this.outlinePaint != null",
                                    "this.backgroundPaint != null",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.outlineVisible == true",
                                    "this.insets != null",
                                    "this.backgroundAlpha == 1.0",
                                    "this.drawingSupplier != null",
                                    "this.outlinePaint has only one value",
                                    "this.listenerList != null",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.noDataMessagePaint != null",
                                    "this.noDataMessageFont != null"
                                ]
                            }
                        }
                    ]
                }
            ]
        },
        {
            "class$(java.lang.String)": [
                {
                    "ENTER": [
                        {
                            "Patch86.inv.output": {
                                "invs": [
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener == null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        },
                        {
                            "f.inv.output": {
                                "invs": [
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener == null"
                                ]
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "Patch86.inv.output": {
                                "invs": [
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener == null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        },
                        {
                            "f.inv.output": {
                                "invs": [
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener == null"
                                ]
                            }
                        }
                    ]
                }
            ]
        },
        {
            "setOutlinePaint(java.awt.Paint)": [
                {
                    "ENTER": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "paint != null",
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.outlineStroke != null",
                                    "this.outlinePaint != null",
                                    "this.outlineStroke has only one value",
                                    "this.backgroundPaint != null",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.outlineVisible == true",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.backgroundPaint has only one value",
                                    "this.insets != null",
                                    "this.noDataMessagePaint != null",
                                    "this.noDataMessagePaint has only one value",
                                    "this.listenerList != null",
                                    "this.backgroundAlpha == 1.0",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "this.drawingSupplier != null",
                                    "this.noDataMessageFont != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.outlineStroke != null",
                                    "this.outlinePaint != null",
                                    "this.outlineStroke has only one value",
                                    "this.backgroundPaint != null",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.outlineVisible == true",
                                    "this.backgroundPaint has only one value",
                                    "this.insets != null",
                                    "this.backgroundAlpha == 1.0",
                                    "this.noDataMessagePaint has only one value",
                                    "this.listenerList != null",
                                    "this.drawingSupplier != null",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "this.noDataMessagePaint != null",
                                    "this.noDataMessageFont != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                },
                {
                    "EXITNN": [
                        {
                            "861": [
                                {
                                    "f.inv.output": {
                                        "invs": []
                                    }
                                },
                                {
                                    "b.inv.output": {
                                        "invs": []
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "fireChangeEvent()": [
                {
                    "ENTER": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.outlineStroke != null",
                                    "this.outlinePaint != null",
                                    "this.outlineStroke has only one value",
                                    "this.backgroundPaint != null",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.outlineVisible == true",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.backgroundPaint has only one value",
                                    "this.insets != null",
                                    "this.noDataMessagePaint != null",
                                    "this.noDataMessagePaint has only one value",
                                    "this.listenerList != null",
                                    "this.backgroundAlpha == 1.0",
                                    "this.drawingSupplier != null",
                                    "this.noDataMessageFont != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.outlineStroke != null",
                                    "this.outlinePaint != null",
                                    "this.outlineStroke has only one value",
                                    "this.backgroundPaint != null",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.outlineVisible == true",
                                    "this.backgroundPaint has only one value",
                                    "this.insets != null",
                                    "this.backgroundAlpha == 1.0",
                                    "this.noDataMessagePaint has only one value",
                                    "this.listenerList != null",
                                    "this.drawingSupplier != null",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.noDataMessagePaint != null",
                                    "this.noDataMessageFont != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                }
            ]
        },
        {
            "addChangeListener(org.jfree.chart.event.PlotChangeListener)": [
                {
                    "ENTER": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.outlineStroke != null",
                                    "this.outlinePaint != null",
                                    "this.backgroundPaint != null",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.outlineVisible == true",
                                    "this.backgroundImageAlpha == 0.5",
                                    "listener != null",
                                    "this.insets != null",
                                    "this.noDataMessagePaint != null",
                                    "this.backgroundAlpha == 1.0",
                                    "this.listenerList != null",
                                    "this.drawingSupplier != null",
                                    "this.noDataMessageFont != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": [
                                    "this.outlinePaint has only one value"
                                ]
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.outlineStroke != null",
                                    "this.outlinePaint != null",
                                    "this.backgroundPaint != null",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.outlineVisible == true",
                                    "this.insets != null",
                                    "this.backgroundAlpha == 1.0",
                                    "this.drawingSupplier != null",
                                    "this.listenerList != null",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "this.noDataMessagePaint != null",
                                    "this.noDataMessageFont != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": [
                                    "this.outlinePaint has only one value"
                                ]
                            }
                        }
                    ]
                }
            ]
        },
        {
            "setDrawingSupplier(org.jfree.chart.plot.DrawingSupplier)": [
                {
                    "ENTER": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.outlineStroke != null",
                                    "this.outlinePaint != null",
                                    "this.outlineStroke has only one value",
                                    "this.backgroundPaint != null",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.outlineVisible == true",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.backgroundPaint has only one value",
                                    "this.insets != null",
                                    "supplier != null",
                                    "this.noDataMessagePaint != null",
                                    "this.noDataMessagePaint has only one value",
                                    "this.listenerList != null",
                                    "this.backgroundAlpha == 1.0",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "this.drawingSupplier != null",
                                    "this.noDataMessageFont != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.outlineStroke != null",
                                    "this.outlinePaint != null",
                                    "this.outlineStroke has only one value",
                                    "this.backgroundPaint != null",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.outlineVisible == true",
                                    "this.backgroundPaint has only one value",
                                    "this.insets != null",
                                    "this.backgroundAlpha == 1.0",
                                    "this.noDataMessagePaint has only one value",
                                    "this.listenerList != null",
                                    "this.drawingSupplier != null",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "this.noDataMessagePaint != null",
                                    "this.noDataMessageFont != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                }
            ]
        },
        {
            "axisChanged(org.jfree.chart.event.AxisChangeEvent)": [
                {
                    "ENTER": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "event.axis.plot != null",
                                    "event.axis.listenerList != null",
                                    "org.jfree.chart.axis.Axis.DEFAULT_AXIS_LINE_STROKE != null",
                                    "event.axis.tickLabelInsets != null",
                                    "this.backgroundPaint != null",
                                    "this.outlineStroke has only one value",
                                    "event.axis.axisLineStroke != null",
                                    "event.axis.tickMarkPaint != null",
                                    "this.insets != null",
                                    "event.axis.labelFont != null",
                                    "this.drawingSupplier != null",
                                    "event.axis != null",
                                    "org.jfree.chart.axis.Axis.DEFAULT_AXIS_LINE_PAINT != null",
                                    "event.axis.tickLabelPaint != null",
                                    "org.jfree.chart.event.ChartChangeEventType.NEW_DATASET != null",
                                    "event.axis.label != null",
                                    "org.jfree.chart.axis.Axis.DEFAULT_TICK_LABEL_INSETS != null",
                                    "org.jfree.chart.event.ChartChangeEventType.GENERAL != null",
                                    "event.type != null",
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "event != null",
                                    "org.jfree.chart.JFreeChart.INFO != null",
                                    "event.type.name != null",
                                    "this.backgroundImageAlpha == 0.5",
                                    "org.jfree.chart.axis.Axis.DEFAULT_AXIS_LABEL_INSETS != null",
                                    "org.jfree.chart.axis.Axis.DEFAULT_TICK_MARK_PAINT != null",
                                    "org.jfree.chart.axis.Axis.DEFAULT_AXIS_LABEL_FONT != null",
                                    "this.noDataMessagePaint != null",
                                    "this.noDataMessageFont != null",
                                    "event.axis.labelPaint != null",
                                    "org.jfree.chart.event.ChartChangeEventType.DATASET_UPDATED != null",
                                    "event.axis.tickMarkStroke != null",
                                    "this.outlinePaint != null",
                                    "this.notify == true",
                                    "this.outlineVisible == true",
                                    "event.axis.axisLinePaint != null",
                                    "this.backgroundAlpha == 1.0",
                                    "org.jfree.chart.axis.Axis.DEFAULT_TICK_LABEL_FONT != null",
                                    "org.jfree.chart.axis.Axis.DEFAULT_TICK_MARK_STROKE != null",
                                    "this.noDataMessagePaint has only one value",
                                    "event.axis.tickLabelFont != null",
                                    "org.jfree.chart.axis.Axis.DEFAULT_AXIS_LABEL_PAINT != null",
                                    "this.listenerList != null",
                                    "org.jfree.chart.JFreeChart.DEFAULT_BACKGROUND_PAINT != null",
                                    "org.jfree.chart.JFreeChart.DEFAULT_TITLE_FONT != null",
                                    "this.outlineStroke != null",
                                    "this.backgroundImageAlignment == 15",
                                    "org.jfree.chart.axis.Axis.DEFAULT_TICK_LABEL_PAINT != null",
                                    "event.axis.labelInsets != null",
                                    "org.jfree.chart.axis.Axis.class$org$jfree$chart$event$AxisChangeListener != null",
                                    "this.backgroundPaint has only one value",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": [
                                    "this has only one value",
                                    "this.drawingSupplier has only one value",
                                    "org.jfree.chart.JFreeChart.class$org$jfree$chart$event$ChartChangeListener == null",
                                    "event.axis.label.toString one of { \"X\", \"Y\" }",
                                    "this.listenerList has only one value",
                                    "this.noDataMessageFont has only one value",
                                    "event.axis.getClass().getName() == org.jfree.chart.axis.NumberAxis.class",
                                    "event.axis.plot has only one value"
                                ]
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "event.axis.tickLabelInsets != null",
                                    "event.axis.plot != null",
                                    "event.axis.listenerList != null",
                                    "org.jfree.chart.axis.Axis.DEFAULT_AXIS_LINE_STROKE != null",
                                    "this.backgroundPaint != null",
                                    "event.axis.axisLineStroke != null",
                                    "this.outlineStroke has only one value",
                                    "event.axis.tickMarkPaint != null",
                                    "this.insets != null",
                                    "event.axis.labelFont != null",
                                    "this.drawingSupplier != null",
                                    "event.axis != null",
                                    "org.jfree.chart.axis.Axis.DEFAULT_AXIS_LINE_PAINT != null",
                                    "event.axis.tickLabelPaint != null",
                                    "org.jfree.chart.event.ChartChangeEventType.NEW_DATASET != null",
                                    "event.axis.label != null",
                                    "org.jfree.chart.axis.Axis.DEFAULT_TICK_LABEL_INSETS != null",
                                    "org.jfree.chart.event.ChartChangeEventType.GENERAL != null",
                                    "event.type != null",
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "org.jfree.chart.JFreeChart.INFO != null",
                                    "event.type.name != null",
                                    "this.backgroundImageAlpha == 0.5",
                                    "org.jfree.chart.axis.Axis.DEFAULT_AXIS_LABEL_INSETS != null",
                                    "org.jfree.chart.axis.Axis.DEFAULT_TICK_MARK_PAINT != null",
                                    "org.jfree.chart.axis.Axis.DEFAULT_AXIS_LABEL_FONT != null",
                                    "this.noDataMessagePaint != null",
                                    "this.noDataMessageFont != null",
                                    "event.axis.labelPaint != null",
                                    "org.jfree.chart.event.ChartChangeEventType.DATASET_UPDATED != null",
                                    "event.axis.tickMarkStroke != null",
                                    "this.outlinePaint != null",
                                    "this.notify == true",
                                    "this.outlineVisible == true",
                                    "event.axis.axisLinePaint != null",
                                    "event.axis.tickLabelFont != null",
                                    "this.backgroundAlpha == 1.0",
                                    "org.jfree.chart.axis.Axis.DEFAULT_TICK_LABEL_FONT != null",
                                    "org.jfree.chart.axis.Axis.DEFAULT_TICK_MARK_STROKE != null",
                                    "this.noDataMessagePaint has only one value",
                                    "org.jfree.chart.axis.Axis.DEFAULT_AXIS_LABEL_PAINT != null",
                                    "this.listenerList != null",
                                    "org.jfree.chart.JFreeChart.DEFAULT_BACKGROUND_PAINT != null",
                                    "org.jfree.chart.JFreeChart.DEFAULT_TITLE_FONT != null",
                                    "this.outlineStroke != null",
                                    "this.backgroundImageAlignment == 15",
                                    "org.jfree.chart.axis.Axis.DEFAULT_TICK_LABEL_PAINT != null",
                                    "event.axis.labelInsets != null",
                                    "org.jfree.chart.axis.Axis.class$org$jfree$chart$event$AxisChangeListener != null",
                                    "this.backgroundPaint has only one value",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": [
                                    "this.drawingSupplier has only one value",
                                    "org.jfree.chart.JFreeChart.class$org$jfree$chart$event$ChartChangeListener == null",
                                    "event.axis.label.toString one of { \"X\", \"Y\" }",
                                    "this.listenerList has only one value",
                                    "this.noDataMessageFont has only one value",
                                    "event.axis.getClass().getName() == org.jfree.chart.axis.NumberAxis.class",
                                    "event.axis.plot has only one value"
                                ]
                            }
                        }
                    ]
                }
            ]
        },
        {
            "setBackgroundPaint(java.awt.Paint)": [
                {
                    "ENTER": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "paint != null",
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.outlineStroke != null",
                                    "this.outlinePaint != null",
                                    "this.outlineStroke has only one value",
                                    "this.backgroundPaint != null",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.outlineVisible == true",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.backgroundPaint has only one value",
                                    "this.insets != null",
                                    "this.noDataMessagePaint != null",
                                    "this.noDataMessagePaint has only one value",
                                    "this.listenerList != null",
                                    "this.backgroundAlpha == 1.0",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "this.drawingSupplier != null",
                                    "this.noDataMessageFont != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.outlineStroke != null",
                                    "this.outlinePaint != null",
                                    "this.outlineStroke has only one value",
                                    "this.backgroundPaint != null",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.outlineVisible == true",
                                    "this.backgroundPaint has only one value",
                                    "this.insets != null",
                                    "this.backgroundAlpha == 1.0",
                                    "this.noDataMessagePaint has only one value",
                                    "this.listenerList != null",
                                    "this.drawingSupplier != null",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "this.noDataMessagePaint != null",
                                    "this.noDataMessageFont != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                },
                {
                    "EXITNN": [
                        {
                            "575": [
                                {
                                    "f.inv.output": {
                                        "invs": []
                                    }
                                },
                                {
                                    "b.inv.output": {
                                        "invs": []
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "Plot()": [
                {
                    "EXIT": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "this.outlineStroke != null",
                                    "this.outlinePaint != null",
                                    "this.outlineStroke has only one value",
                                    "this.backgroundPaint != null",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.outlineVisible == true",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.backgroundPaint has only one value",
                                    "this.insets != null",
                                    "this.noDataMessagePaint != null",
                                    "this.noDataMessagePaint has only one value",
                                    "this.listenerList != null",
                                    "this.backgroundAlpha == 1.0",
                                    "this.drawingSupplier != null",
                                    "this.noDataMessageFont != null",
                                    "this.foregroundAlpha == 1.0"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                }
            ]
        },
        {
            "setInsets(org.jfree.chart.util.RectangleInsets, boolean)": [
                {
                    "ENTER": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "this.backgroundImageAlignment == 15",
                                    "this.outlineStroke has only one value",
                                    "this.notify == true",
                                    "this.outlineVisible == true",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener has only one value",
                                    "this.backgroundAlpha == 1.0",
                                    "this.noDataMessagePaint has only one value",
                                    "this.backgroundPaint has only one value",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.foregroundAlpha == 1.0"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": [
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener == null"
                                ]
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "this.outlineStroke has only one value",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.outlineVisible == true",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener has only one value",
                                    "this.backgroundAlpha == 1.0",
                                    "this.noDataMessagePaint has only one value",
                                    "this.backgroundPaint has only one value",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.foregroundAlpha == 1.0"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": [
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener == null"
                                ]
                            }
                        }
                    ]
                }
            ]
        },
        {
            "getBackgroundPaint()": [
                {
                    "ENTER": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.outlineStroke != null",
                                    "this.outlinePaint != null",
                                    "this.outlineStroke has only one value",
                                    "this.backgroundPaint != null",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.outlineVisible == true",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.backgroundPaint has only one value",
                                    "this.insets != null",
                                    "this.noDataMessagePaint != null",
                                    "this.noDataMessagePaint has only one value",
                                    "this.listenerList != null",
                                    "this.backgroundAlpha == 1.0",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "this.drawingSupplier != null",
                                    "this.noDataMessageFont != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.outlineStroke != null",
                                    "this.outlinePaint != null",
                                    "this.outlineStroke has only one value",
                                    "this.backgroundPaint != null",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.backgroundImageAlpha == 0.5",
                                    "return != null",
                                    "this.outlineVisible == true",
                                    "this.backgroundPaint has only one value",
                                    "this.insets != null",
                                    "this.backgroundAlpha == 1.0",
                                    "this.noDataMessagePaint has only one value",
                                    "this.listenerList != null",
                                    "this.drawingSupplier != null",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "this.noDataMessagePaint != null",
                                    "this.noDataMessageFont != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": []
                            }
                        }
                    ]
                }
            ]
        },
        {
            "getDrawingSupplier()": [
                {
                    "ENTER": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.outlineStroke != null",
                                    "this.outlinePaint != null",
                                    "this.outlineStroke has only one value",
                                    "this.backgroundPaint != null",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.outlineVisible == true",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.backgroundPaint has only one value",
                                    "this.insets != null",
                                    "this.noDataMessagePaint != null",
                                    "this.noDataMessagePaint has only one value",
                                    "this.listenerList != null",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "this.backgroundAlpha == 1.0",
                                    "this.drawingSupplier != null",
                                    "this.noDataMessageFont != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": [
                                    "this.outlinePaint has only one value"
                                ]
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.outlineStroke != null",
                                    "this.outlinePaint != null",
                                    "this.outlineStroke has only one value",
                                    "this.backgroundPaint != null",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.backgroundImageAlpha == 0.5",
                                    "return != null",
                                    "this.outlineVisible == true",
                                    "this.backgroundPaint has only one value",
                                    "this.insets != null",
                                    "this.backgroundAlpha == 1.0",
                                    "this.noDataMessagePaint has only one value",
                                    "this.listenerList != null",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener != null",
                                    "this.drawingSupplier != null",
                                    "this.noDataMessagePaint != null",
                                    "this.noDataMessageFont != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": [
                                    "this.outlinePaint has only one value"
                                ]
                            }
                        }
                    ]
                }
            ]
        },
        {
            "notifyListeners(org.jfree.chart.event.PlotChangeEvent)": [
                {
                    "ENTER": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "event.plot.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.outlineStroke != null",
                                    "this.outlinePaint != null",
                                    "this.backgroundPaint != null",
                                    "this.notify == true",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.backgroundImageAlignment == 15",
                                    "this.outlineVisible == true",
                                    "this.insets != null",
                                    "this.backgroundAlpha == 1.0",
                                    "this.listenerList != null",
                                    "this.drawingSupplier != null",
                                    "this.noDataMessagePaint != null",
                                    "this.noDataMessageFont != null"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": [
                                    "org.jfree.chart.JFreeChart.class$org$jfree$chart$event$ChartChangeListener == null",
                                    "event.plot.foregroundAlpha == 1.0",
                                    "event.plot.noDataMessagePaint has only one value",
                                    "event.plot.outlineStroke has only one value",
                                    "event.plot.backgroundPaint has only one value"
                                ]
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "this.backgroundPaint != null",
                                    "this.insets != null",
                                    "this.drawingSupplier != null",
                                    "size(event.chart.subtitles[]) one of { 0, 1 }",
                                    "this.foregroundAlpha one of { 0.5, 1.0 }",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.noDataMessagePaint != null",
                                    "this.noDataMessageFont != null",
                                    "event.plot.foregroundAlpha one of { 0.5, 1.0 }",
                                    "event.chart.subtitles[].getClass().getName() one of { [], [org.jfree.chart.title.LegendTitle] }",
                                    "this.outlinePaint != null",
                                    "this.notify == true",
                                    "this.outlineVisible == true",
                                    "this.backgroundAlpha == 1.0",
                                    "this.listenerList != null",
                                    "this.outlineStroke != null",
                                    "this.backgroundImageAlignment == 15"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": [
                                    "event.plot.foregroundAlpha == 1.0",
                                    "event.plot.noDataMessagePaint has only one value",
                                    "event.plot.outlineStroke has only one value",
                                    "event.chart.borderPaint has only one value",
                                    "org.jfree.chart.JFreeChart.class$org$jfree$chart$event$ChartChangeListener == null",
                                    "size(event.chart.subtitles[]) == 1",
                                    "event.chart.padding has only one value",
                                    "event.chart.subtitles[].getClass().getName() == [org.jfree.chart.title.LegendTitle]",
                                    "event.chart.backgroundPaint has only one value",
                                    "event.plot.backgroundPaint has only one value"
                                ]
                            }
                        }
                    ]
                },
                {
                    "EXITNN": [
                        {
                            "971": [
                                {
                                    "f.inv.output": {
                                        "invs": []
                                    }
                                },
                                {
                                    "b.inv.output": {
                                        "invs": []
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "setInsets(org.jfree.chart.util.RectangleInsets)": [
                {
                    "ENTER": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "this.backgroundImageAlignment == 15",
                                    "this.outlineStroke has only one value",
                                    "this.notify == true",
                                    "this.outlineVisible == true",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener has only one value",
                                    "this.backgroundAlpha == 1.0",
                                    "this.noDataMessagePaint has only one value",
                                    "this.backgroundPaint has only one value",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.foregroundAlpha == 1.0"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": [
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener == null"
                                ]
                            }
                        }
                    ]
                },
                {
                    "EXIT": [
                        {
                            "f.inv.output": {
                                "invs": [
                                    "this.outlineStroke has only one value",
                                    "this.backgroundImageAlignment == 15",
                                    "this.notify == true",
                                    "this.outlineVisible == true",
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener has only one value",
                                    "this.backgroundAlpha == 1.0",
                                    "this.noDataMessagePaint has only one value",
                                    "this.backgroundPaint has only one value",
                                    "this.backgroundImageAlpha == 0.5",
                                    "this.foregroundAlpha == 1.0"
                                ]
                            }
                        },
                        {
                            "b.inv.output": {
                                "invs": [
                                    "org.jfree.chart.plot.Plot.class$org$jfree$chart$event$PlotChangeListener == null"
                                ]
                            }
                        }
                    ]
                }
            ]
        }
    ]
}